# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.textBrowser = QtWidgets.QTextBrowser(MainWindow)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.textBrowser)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menuFormula = QtWidgets.QMenu(self.menubar)
        self.menuFormula.setObjectName("menuFormula")
        self.menuDocument = QtWidgets.QMenu(self.menubar)
        self.menuDocument.setObjectName("menuDocument")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAS = QtWidgets.QAction(MainWindow)
        self.actionSaveAS.setObjectName("actionSaveAS")
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.actionList_all = QtWidgets.QAction(MainWindow)
        self.actionList_all.setObjectName("actionList_all")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.menuFormula.addAction(self.actionNew)
        self.menuFormula.addAction(self.actionOpen)
        self.menuFormula.addAction(self.actionSave)
        self.menuFormula.addAction(self.actionSaveAS)
        self.menuFormula.addSeparator()
        self.menuFormula.addAction(self.actionFilter)
        self.menuFormula.addAction(self.actionList_all)
        self.menuDocument.addAction(self.actionCreate)
        self.menuDocument.addAction(self.actionSearch)
        self.menuDocument.addSeparator()
        self.menuDocument.addAction(self.actionExecute)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menubar.addAction(self.menuFormula.menuAction())
        self.menubar.addAction(self.menuDocument.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFormula.setTitle(_translate("MainWindow", "Formula"))
        self.menuDocument.setTitle(_translate("MainWindow", "Work"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAS.setText(_translate("MainWindow", "SaveAs"))
        self.actionFilter.setText(_translate("MainWindow", "Filter"))
        self.actionList_all.setText(_translate("MainWindow", "List all"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAboutQt.setText(_translate("MainWindow", "About Qt"))

